[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "tavily-company-research"
version = "0.1.0"
description = "Company research tool using Tavily"
requires-python = ">=3.11"

[tool.setuptools.packages.find]
where = ["src"]
include = ["backend*"] 